id: IA692892F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T07:37:48+00:00'
last_modified: '2022-06-08T01:07:58.817756+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18772
  title: གྲོང་གསེབ་ཀྱི་ཏང་རྩ་འཛུགས་འཛུགས་སྐྱོང་བྱེད་ཕྱོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    59B3:
      image_group_id: I8LS18774
      title: ''
      total_pages: 419
      order: 1
      base_file: 59B3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
